### ISSUE TITLE
playtone does not play any sound

### ISSUE THREAD

**Issue by Alklas** [switchbrew/switch-examples#10]
hello
just tried HBL + playtone, while undocked, on the internal screen and with no external power

it does not sound anything 

i tried pushing the keys but no difference

other examples are working fine ( hello world, simple gfx )

**Comment by yellows8** [comment]
volume?

**Comment by Alklas** [comment]
volume is at the max
sound is ok in the menus
i built my own sample test using libtransistor, and it works fine ( not through HBL of course but using node+pegaswitch+ace)
just checked volume level while using playtone, volume is ok, still no sound
the only key doing something is + to leave the application

**Comment by yellows8** [comment]
Tested again & it works fine here.

**Comment by yellows8** [comment]
Are both joy-cons attached/detached? Nothing connected with USB?

**Comment by Alklas** [comment]
both joy cons are attached, nothing on usb. no power attached. 
i will check deeper this evening, i will try to build my own code, removing SIN function for a direct = function to have a high volume sound.
( HBL is an improvment for end user, but not for coder as this involves removing the SD, which involves rebooting, and pegaswitch + hbl does not work 100%)

**Comment by Alklas** [comment]
test done right now : 
- printf after a touch is pressed, working fine, the keys are detected
- s16 sample = 0x7FFF; instead of SIN, still no sound.

i also tried to upload the playtone nro through pegaswitch+ace, but it is a pity it does not work.

**Comment by Alklas** [comment]
i also tried with sample = 0xFFF
and then tried it with dock + TV
always the same issue

could that be linked to the fact that i own an European Switch, running in french language ?
Serial: XAJ7000777XXXX

**Comment by Alklas** [comment]
with the release of libtransistor 1.1.2, i downloaded their already built nro, run them through HBL, and the test_audio_output.nro is working fine, i can ear the 12 seconds ta ta ta ta :)

there seems to be an issue with libnx for audio

**Comment by yellows8** [comment]
A fix is being worked on (see PR).

**Comment by Alklas** [comment]
great !
i hope my inputs can help :)

**Comment by Alklas** [comment]
i just built last libnx, and then rebuilt playtone, issue fixed 
thanks
