### ISSUE TITLE
fs/sdmc example are not supported chinese characters

### ISSUE THREAD

**Issue by baiXfeng** [switchbrew/switch-examples#106]
I am a Chinese developer. I want to traverse and access files with Chinese characters on the disk. I searched a lot of information with Google, and also read the source code related to devkitPro/switch. I also tried to use some low-level interfaces to traverse the disk files, but all failed. How can I traverse and read and write files containing Chinese characters?

**Comment by fincs** [comment]
This is a known issue that unfortunately cannot be fixed without reimplementing the FS sysmodule. The FAT driver Nintendo used is incorrectly configured to assume filenames are encoded as Shift-JIS, even though the rest of the system uses UTF-8.
