### ISSUE TITLE
Image in simplegfx will not load? (whats the correct compile flag)

### ISSUE THREAD

**Issue by futurepr0n** [switchbrew/switch-examples#11]
Hi all,

can anyone help me with simplgfx switch demo? I tried creating a file image.bin from  a 1280x720p png, but I cant get the right compile flags I guess, becase the object is never created and the greyscale loop is loaded instead of the image. last night i was told to run make CFLAGS=-DLOAD_IMAGE but this did not work,

If I straight compile using make, but set my directory structure up where source\data\image.bin exists (see below at my fork), I still end up not bringing the binary object in and it is not inclued in the .nro that results.

https://github.com/futurepr0n/switch-examples/tree/master/graphics/simplegfx/source

**Comment by notquiteapex** [comment]
the correct flag is you'll want to set DISPLAY_IMAGE. just do `CFLAGS=-DDISPLAY_IMAGE`.

dont be afraid of looking through the code ;P

**Comment by futurepr0n** [comment]
Yeah, I only noticed that now - someone told me it was "LOAD_IMAGE" and I didn;t understand at first how it was used. Now I do, thank you.
