### ISSUE TITLE
Trying to run simplegfx

### ISSUE THREAD

**Issue by wgcv** [switchbrew/switch-examples#14]
When i try to compile and run simplegfx give me a black screen in the emulator, I put the RGB888 image.bin in .data/image.bin also in ./source/data/image.bin. I don't have now a Nintendo switch, but the hello world work fine. 
I'm using nightly-mingw emulator
![untitled](https://user-images.githubusercontent.com/8989089/36469570-a8d8e9c0-16b5-11e8-8004-7e50b3b94eed.png)

**Comment by WinterMute** [comment]
image.bin only needs to be in data/image.bin

You also need to enable DISPLAY_IMAGE :- see https://github.com/switchbrew/switch-examples/blob/master/graphics/simplegfx/source/main.c#L5 & https://github.com/switchbrew/switch-examples/blob/master/graphics/simplegfx/source/main.c#L57

Just add `#define DISPLAY_IMAGE` to the top of main.c

**Comment by yellows8** [comment]
AFAIK yuzu is broken for libnx-doublebuffering.

**Comment by wgcv** [comment]
@WinterMute I add #define DISPLAY_IMAGE but nothing, i think that is the emulator like yellows8 says.
@yellows8 You knwo some emulator that i can use?

**Comment by yellows8** [comment]
https://github.com/gdkchan/Ryujinx

**Comment by wgcv** [comment]
Solved @yellows8 thanks
