### ISSUE TITLE
Make failing on template/simple

### ISSUE THREAD

**Issue by kapeas** [switchbrew/switch-examples#3]
Hi. I am finding some trouble building the simple example. Probably my environment setup is not 100% correct. When running make, it outputs:

I created an exefs_src/a folder as recommended [here](https://gist.github.com/vgmoose/8844a812c4bf50889e3f2b65359a6930):

```
francisco@francisco-XPS-13-9360:~/devkitpro/switch-examples/templates/simple$ make
main.c
aarch64-none-elf-gcc -MMD -MP -MF /home/francisco/devkitpro/switch-examples/templates/simple/build/main.d -g -Wall -O2 -ffast-math -march=armv8-a -mtp=soft -fPIE  -I/home/francisco/devkitpro/switch-examples/templates/simple/include -I/home/francisco/devkitpro/portlibs/armv8-a/include -I/home/francisco/devkitpro/portlibs/switch/include -I/home/francisco/devkitpro/libnx/include -I/home/francisco/devkitpro/switch-examples/templates/simple/build -DSWITCH -c /home/francisco/devkitpro/switch-examples/templates/simple/source/main.c -o main.o 
linking simple.elf
built ... simple.nso
Directories aren't supported, skipping... (exefs/a)
built ... simple.pfs0
built ... simple.nacp
Failed to open input icon!
/home/francisco/devkitpro/devkitA64/switch_rules:47: fallo en las instrucciones para el objetivo '/home/francisco/devkitpro/switch-examples/templates/simple/simple.nro'
make[1]: *** [/home/francisco/devkitpro/switch-examples/templates/simple/simple.nro] Error 1
Makefile:140: fallo en las instrucciones para el objetivo 'build'
make: *** [build] Error 2
```

that line 47 of switch-rules contains
`@elf2nro $< $@ $(NROFLAGS)`

EDIT1:
Makefile:140
  @[ -d $@ ] || mkdir -p $@

EDIT2: I have just seen the comment below those instructions that they are not precise. Anyway, I should build that with make, right?

Hope this helps. Thanks in advance!

**Comment by yellows8** [comment]
"I created an exefs_src/a folder " That's outdated, not needed anymore.

Do you have any .jpg files under the example directory? Are you using latest libnx with the default_icon.jpg file?

**Comment by kapeas** [comment]
Hi, thanks for the answer. My libnx root folder did not contain the default_icon.jpg file. Adding it there solved the problem. Built correctly I think. Now time to set up pegaswitch and start messing around :)
