### ISSUE TITLE
No examples are compiling

### ISSUE THREAD

**Issue by soymjolk** [switchbrew/switch-examples#32]
Probably because of how my environment is set up, but still, I'm stuck. After running "make" in the hello-world directory, I get one of two errors: "/Users/[username]/devkitPro/devkitARM/bin/../lib/gcc/arm-none-eabi/7.1.0/../../../../arm-none-eabi/bin/ld: cannot represent machine `aarch64'" or "make[1]: *** [main.o] Error 1
make: *** [build] Error 2".

For the main.o error, I've tried running "touch main.o" in the build directory and I believe that's fixed it. However, for the aarch64 error, I don't really know how to fix or troubleshoot that. I might try reinstalling DKA and seeing if that works.

Thanks for all your work!

**Comment by soymjolk** [comment]
Update: reinstalling DKA and DKA64 had no effect on anything ):

**Comment by WinterMute** [comment]
delete /Users/[username]/devkitPro then grab the appropriate pacman package from https://github.com/devkitPro/pacman/releases/latest.

For OSX you'll currently need to set DEVKITPRO manually. Once you have pacman installed use `sudo dkp-pacman -S switch-dev` to get the latest switch tools.

**Comment by soymjolk** [comment]
I tried installing both 1.0.0 and 1.0.1, both of them came back with this: 
<img width="622" alt="devkitPro installation failure" src="https://user-images.githubusercontent.com/34921800/40630935-3049b4a8-62a5-11e8-8d1c-86425cec0b6a.png">

**Comment by WinterMute** [comment]
This is unrelated to switch examples.Please open an issue @ https://github.com/devkitpro/pacman/issues with full details of your system.
