### ISSUE TITLE
irsensor and vibration example not working

### ISSUE THREAD

**Issue by MingchenZhang** [switchbrew/switch-examples#34]
I tested the irsensor and vibration example and they didn't work. The irsensor example just gives a black screen after the prompts disappears (joycon detached). The vibration example initialize the vibration and sends values successfully, but no actual vibration appear on the joycon. 

On horizon 5.1.0, using Hekate/Atmosphere

**Comment by fincs** [comment]
I have the same issue, reproduced slightly over a week ago.

**Comment by MingchenZhang** [comment]
I suppose i need to bring this issue to libnx? Maybe horizon restrict or change certain interface in newer firmware?

**Comment by akacyra** [comment]
Same setup, reproduced for IR example. Threw in a print statement, and error is returned on [this line](https://github.com/switchbrew/switch-examples/blob/13000dfd88449200e495b83203a95edf4a0988d2/hid/irsensor/source/main.c#L90). Error code is `0xf0cd`: module is `0xcd`, description is `0x78`. According to [the wiki](http://switchbrew.org/index.php?title=Error_codes), `0xcd` is the IR module, but there is no documented description for `0x78`.

**Comment by yellows8** [comment]
See https://github.com/switchbrew/libnx/issues/148 for current status.
