### ISSUE TITLE
Missing nacptool

### ISSUE THREAD

**Issue by Rinnegatamante** [switchbrew/switch-examples#4]
After setting up devkitA64 and installing libnx, whenever i try to compile a sample i get a Command not found error related to nacptool.
Googling a bit didn't solve my problem since i didn't find any info about this tool.
devkitA64 version i installed is the Alpha 5 available on sourceforge.
![nacptool](https://user-images.githubusercontent.com/9152710/35043764-17d5a252-fb8e-11e7-9e84-0db5620ed28d.png)

**Comment by notquiteapex** [comment]
its in switch-tools, you'll have to build it yourself as it isn't included in devkitA64 yet.

**Comment by plutooo** [comment]
Will be fixed with devkitA64 a6
