### ISSUE TITLE
Textured Cube Not Working

### ISSUE THREAD

**Issue by niko1point0** [switchbrew/switch-examples#46]
I tried compiling and running the Textured Cube sample on the Nintendo Switch Emulator called Yuzu, and it did not work. Has anyone tried running the Textured Cube sample on a physical Nintendo Switch?

**Comment by fincs** [comment]
Example works on hardware, yuzu is at fault. Please report it to [them](https://github.com/yuzu-emu/yuzu/issues).

**Comment by niko1point0** [comment]
Thank you
