### ISSUE TITLE
I made a 3D Model Loader for Switch, can you post it to the Samples Folder?

### ISSUE THREAD

**Issue by niko1point0** [switchbrew/switch-examples#47]
https://drive.google.com/file/d/1m39E1kA5oFO9m0E_UXovZx6ebNJPuHSk/view?usp=sharing

I have been experimenting with the SwitchBrew Open Source SDK, and I have a few questions.
There are multiple ways where this project could be improved, maybe you can help me.
I want this project to be available to everyone, so that people can make Homebrew Switch games.

The SDK has a feature where PNGs are compiled into .o files, and then a .h
file is given to access the compiled PNG data

Here I wrote a fully working OBJ loader for Nintendo Switch
Right now I use pbr_cube\data\Model\program.pl to convert OBJ model to .h file

I use this command "perl Obj2OpenGL.pl ./gun.obj" and it generates "gun.h", which I rename to "Gun_obj.h"

Here's the problem, I cannot convert the arrays to a compiled .o
That means, when I use #include "Gun_obj.h" it has to recompile the data arrays every time
Can you find a way to automatically convert the OBJ model into .o and .h in a similar
	way to how you do it with PNG?

Can you post this in the Samples folder on Github? I give full consent to making this code open source
I took your textured_cube sample, and added support for Specular Mapping, and Ambient Occlusion mapping,
in addition to diffuse mapping.

Also, in lines 387 - 400 of main.cpp, I have to construct the Vertex array, out of three arrays that OBJ2OpenGL exports.
Can you make it so the full Vertex array is generated and compiled before the program launches?

Thank you!

**Comment by fincs** [comment]
If you have something to contribute, feel free to submit a Pull Request.

**Comment by niko1point0** [comment]
I'm not sure how

**Comment by fincs** [comment]
A good starting point would be this:

**Comment by fincs** [comment]
Another thing to add: you might be interested in talking to us directly through IRC (EFnet #3dsdev). We can provide help to solve your build system issue before you submit a PR.

**Comment by niko1point0** [comment]
I submitted a pull request

**Comment by niko1point0** [comment]
It fully works at the moment, but it can be better. I can push again later. How do I use IRC?

**Comment by fincs** [comment]
I use [HexChat](https://hexchat.github.io/).

**Comment by niko1point0** [comment]
Is it IRC4Fun, IRCNet, IRCHighWay?

**Comment by fincs** [comment]
EFnet is the name of the server.

**Comment by fincs** [comment]
I'm going to close this issue, moving to #48.
