### ISSUE TITLE
Shared font example build error.

### ISSUE THREAD

**Issue by LITTOMA** [switchbrew/switch-examples#51]
> aarch64-none-elf-gcc.exe: error: unrecognized command line option '-mms-bitfields'

Build with gcc version 8.2.0 (devkitA64 release 12)

**Comment by mtheall** [comment]
Looks like this probably comes from `freetype-config --cflags`. Can you tell whether it's running devkitA64's freetype-config or your system's?

**Comment by LITTOMA** [comment]
It's running from my system. It built succeed after I installed switch-freetype.



发自我的小米手机
在 mtheall <notifications@github.com>，2019年2月20日 13:41写道：

Looks like this probably comes from freetype-config --cflags. Can you tell whether it's running devkitA64's freetype-config or your system's?
