### ISSUE TITLE
[compile]hwopus-decoder compile problem

### ISSUE THREAD

**Issue by zsword** [switchbrew/switch-examples#56]
When compile hwopus-decoder has some problem.I have already installed switch-portlibs and switch-opusfile.But when i compile the example, it has report "/bin/sh: aarch64-none-elf-pkg-config: command not found" and "..devkitPro/portlibs/switch/include/opus/opusfile.h:110:11: fatal error: opus_multistream.h: No such file or directory # include <opus_multistream.h>".
 My Environment: Windows 10, devkitPro64 & libnx & switch-examples lastest

**Comment by WinterMute** [comment]
Sorry, I guess I closed this prematurely - it was blank when I looked earlier.

from your msys2 shell run `pacman -S switch-pkg-config pkg-config` - that should get you the necessary files. You might also need to add switch-opusfile to that list.

**Comment by zsword** [comment]
Thanks, I have compiled it successfully!
