### ISSUE TITLE
Result cleanup 

### ISSUE THREAD

**Issue by jonyluke** [switchbrew/switch-examples#59]
Result cleanup like in [commit](https://github.com/Atmosphere-NX/Atmosphere/commit/cead8a36ea6409f75307af06d5ea84142ef2424f) from atmosphere

For example, change:
```
rc = fsInitialize();

if (R_FAILED(rc)) {

    fatalSimple(MAKERESULT(Module_Libnx, LibnxError_InitFail_FS));

 }
```
to:

`R_ASSERT(fsInitialize());`

**Comment by yellows8** [comment]
User apps should handle errors properly, no process-termination/{...}.

**Comment by fincs** [comment]
R_ASSERT doesn't exist in libnx. That is a macro that comes from libstratosphere.
