### ISSUE TITLE
switch-examples/applet/libapplets/software-keyboard

### ISSUE THREAD

**Issue by niko1point0** [switchbrew/switch-examples#61]
Hi, I tried to build this keyboard sample, because I would like to include keyboard support for a homebrew that I am working on, but I could not get this sample to compile. I'm getting linker errors for swkbdInlineLaunchForLibraryApplet, and swkbdInlineSetDecidedCancelCallback

**Comment by yellows8** [comment]
Don't mix stable / git, if you're using stable libnx then use stable switch-examples too.

**Comment by fincs** [comment]
Please wait until we roll new stable libnx/switch-examples releases.

**Comment by niko1point0** [comment]
I ended up using hidKeyboardHeld with HidKeyboardScancode. It worked for everything that I needed it to do
