### ISSUE TITLE
failing sysmodule (general make)

### ISSUE THREAD

**Issue by harddevelop** [switchbrew/switch-examples#65]
when I tried to launch a simple make, console returns this error at finishing of compilation process:

> 
> linking sysmodule.elf
> built ... sysmodule.nso
> Service Access must be an object!
> Failed to parse descriptor json!
> make[2]: *** [/opt/devkitpro/libnx/switch_rules:35: /opt/devkitpro/examples/switch-examples/templates/sysmodule/sysmodule.npdm] Error 1
> make[1]: *** [Makefile:165: build] Error 2
> make[1]: se sale del directorio '/opt/devkitpro/examples/switch-examples/templates/sysmodule'
> make: *** [Makefile:6: all] Error 1

**Comment by yellows8** [comment]
`dkp-pacman -Syu`

**Comment by harddevelop** [comment]
> `dkp-pacman -Syu`

Thanks for the answer, but it was done before open the issue. Anyway everything is up to date.

Everything was prepared like is specified in: https://devkitpro.org/wiki/devkitPro_pacman

**Comment by harddevelop** [comment]
Could be the problem this json (which it's launching the exception) in https://raw.githubusercontent.com/switchbrew/switch-examples/master/templates/sysmodule/sysmodule.json?

I tried to validate this json and shows that there are more than one value with "svcUnknown":

> 
> 			"svcSignalToAddress": "0x35",
> 			"svcUnknown": "0x36",
> 			"svcUnknown": "0x37",
> 			"svcUnknown": "0x38",
> 			"svcUnknown": "0x39",
> 			"svcUnknown": "0x3a",
> 			"svcUnknown": "0x3b",
> 			"svcDumpInfo": "0x3c",

**Comment by yellows8** [comment]
"Service Access must be an object!" This is from an old switch-tools version.
