### ISSUE TITLE
please more example USB HS

### ISSUE THREAD

**Issue by rayPopo** [switchbrew/switch-examples#68]
I wonld write an nro to read from usb midi device,but usb example too sample to do
please update usb example add read data form usb device.
thanks!

**Comment by rayPopo** [comment]
thank you for your post. I use usb example connect Roland SPD-30 usb midi cable, usbHsEpPostBuffer return 0xcc8c
![WechatIMG24](https://user-images.githubusercontent.com/37205327/63637282-900e2a00-c6ad-11e9-912c-8fd685dd6758.jpeg)

**Comment by yellows8** [comment]
Don't just use the usbhs example, actually impl the protocol for your device.

That's a known error with [8.0.0+] with the original example, but the example doesn't impl the protocol for mass-storage either...

**Comment by rayPopo** [comment]
thank you for your post!
but switch usb hs dev too hard to me.
i give up this project
then i will open a new project use arduino dev a midi in single convert to sim gamepad button.
