### ISSUE TITLE
Builds will silently fail if switch-pkg-config is not installed

### ISSUE THREAD

**Issue by bylaws** [switchbrew/switch-examples#79]
If you try to build sdl-audio without pkg-config installed a few warning messages will be produced but rather than failing, an invalid nro with no code at all will be produced. Rather than failing like this it would be desirable to cancel the build with an error.

`/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.1.0/../../../../aarch64-none-elf/bin/ld: warning: cannot find entry symbol _start; defaulting to 0000000000000040
`
^ output from linker

**Comment by WinterMute** [comment]
updating the wrappers to fail if pkg-config isn't present helps a little but will still end up with an invalid .nro https://github.com/devkitPro/pacman-packages/commit/e780a942fbec132dccee23587f6bd5f59d815005

I'm not entirely sure why linking isn't failing here.
