### ISSUE TITLE
SDL2 doesn't compile.

### ISSUE THREAD

**Issue by Nixienea** [switchbrew/switch-examples#84]
I took the application template, put SDL2 in, but it gave a lot of errors.
Turns out that I was missing all the dependencies, but when I add them, EGL gives out so many errors that the terminal can't fit them all.
https://pastebin.com/TSL2xp5U is all it can fit.

**Comment by fincs** [comment]
We have a SDL2 specific example project: <https://github.com/switchbrew/switch-examples/tree/master/graphics/sdl2/sdl2-simple>

The errors you've posted result from incorrect linker settings. Take a look at the Makefile of the project above.
