### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by V10lator** [switchbrew/switch-examples#89]
`Without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work` (Source: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license ).

So you might want to choose a copyleft license ASAP as I bet a lot of devs are lazily copy&pasting from your examples without knowing that they're doing illegal actions!

**Comment by fincs** [comment]
There is clearly a [Creative Commons Public Domain Mark](https://creativecommons.org/publicdomain/mark/1.0/) on the project's readme:

https://github.com/switchbrew/switch-examples/blob/master/README.md
