### ISSUE TITLE
CURL example build error

### ISSUE THREAD

**Issue by nosekefik** [switchbrew/switch-examples#91]
Hi, i trying to build curl example but i get this error.
I can build other libraries perfectly, but this example fails, how can I solve it?

`C:/GIT/switch-examples/network/curl/source/main.c:7:10: fatal error: switch.h: No such file or directory
    7 | #include <switch.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [C:\devkitPro/devkitA64/base_rules:19: main.o] Error 1
make[1]: *** [Makefile:165: build] Error 2
make[1]: Leaving directory '/c/GIT/switch-examples/network/curl'
make: *** [Makefile:12: network/curl/] Error 2`

**Comment by nosekefik** [comment]
Fixed, changing environment variables `C:\devkitPro` to `/c/devkitPro`

**Comment by WinterMute** [comment]
> Fixed, changing environment variables `C:\devkitPro` to `/c/devkitPro`

This is wrong. The installer sets this to `/opt/devkitpro` which is correct. Please do not change the environment variables manually.
