### ISSUE TITLE
ldn example is not scanning any networks

### ISSUE THREAD

**Issue by EmreTech** [switchbrew/switch-examples#96]
Hello, so when I attempt to run the ldn example on my Switch (and adapt the code with my own code), it doesn't detect any nearby Wi-Fi networks even though there are some nearby.

IDK if this is an issue with libnx, switch-examples, or maybe Atmosphere, but I decided to start here just in case.

**Comment by yellows8** [comment]
You are running the ldn app on multiple systems, right? ldn is not for normal wifi networks.

**Comment by EmreTech** [comment]
Oh it's not for normal Wi-Fi networks. I thought it was. Oops
